import { COLS, SEQUENCE_STEPS, VISIBLE_ROWS, type MusicClock, type PieceId, type Snapshot } from "./types";
import { PIECE_COLOR_VAR, cellsOf } from "./pieces";
import type { Juice } from "./juice";
function css(name:string,fallback:string){if(typeof document==="undefined")return fallback;return getComputedStyle(document.documentElement).getPropertyValue(name).trim()||fallback;}
export class Renderer {
  canvas:HTMLCanvasElement;ctx:CanvasRenderingContext2D;w=0;h=0;cell=24;ox=0;oy=0;wellW=0;wellH=0;flashes=new Map<string,number>();
  colors:Record<PieceId,string>={I:"#9a775a",O:"#d5c69a",T:"#bd6550",S:"#87906f",Z:"#c47b4f",J:"#72817b",L:"#a78568"};fg="#ece4d1";
  constructor(canvas:HTMLCanvasElement){this.canvas=canvas;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Canvas no disponible");this.ctx=ctx;this.refresh();}
  refresh(){this.fg=css("--color-fg",this.fg);for(const id of Object.keys(this.colors)as PieceId[])this.colors[id]=css(PIECE_COLOR_VAR[id],this.colors[id]);}
  resize(){const p=this.canvas.parentElement,w=p?.clientWidth??360,h=p?.clientHeight??640,dpr=Math.min(2,window.devicePixelRatio||1);this.w=w;this.h=h;this.canvas.width=Math.floor(w*dpr);this.canvas.height=Math.floor(h*dpr);this.canvas.style.width=`${w}px`;this.canvas.style.height=`${h}px`;this.ctx.setTransform(dpr,0,0,dpr,0,0);this.cell=Math.max(12,Math.floor(Math.min((w-28)/COLS,(h-16)/VISIBLE_ROWS)));this.wellW=this.cell*COLS;this.wellH=this.cell*VISIBLE_ROWS;this.ox=Math.floor((w-this.wellW)/2);this.oy=Math.floor((h-this.wellH)/2);}
  flashCell(col:number,row:number){this.flashes.set(`${col},${row}`,1);}
  cellCenter(col:number,row:number){return{x:this.ox+col*this.cell+this.cell/2,y:this.oy+row*this.cell+this.cell/2};}
  draw(snap:Snapshot,clock:MusicClock,juice:Juice,now:number){const c=this.ctx;c.clearRect(0,0,this.w,this.h);c.fillStyle="#0d0c09";c.fillRect(0,0,this.w,this.h);const off=juice.offset(now);c.save();c.translate(this.ox+off.x,this.oy+off.y+clock.kickPulse*3);c.rotate(off.r);this.well(clock);for(let y=0;y<VISIBLE_ROWS;y++)for(let x=0;x<COLS;x++){const cell=snap.grid[y]![x];if(cell)this.block(x,y,cell.type,1,this.flashes.get(`${x},${y}`)??0);}if(snap.active){for(const[cx,cy]of cellsOf(snap.active.type,snap.active.rot)){const x=snap.active.x+cx!,y=snap.ghostY+cy!;if(y>=0&&y<VISIBLE_ROWS)this.outline(x,y,snap.active.type);}for(const[cx,cy]of cellsOf(snap.active.type,snap.active.rot)){const x=snap.active.x+cx!,y=snap.active.y+cy!;if(y>=0&&y<VISIBLE_ROWS)this.block(x,y,snap.active.type,.95,.1);}}this.scan(clock);this.particles(juice);c.restore();for(const[k,v]of this.flashes){const n=v-.08;if(n<=0)this.flashes.delete(k);else this.flashes.set(k,n);}}
  private well(clock:MusicClock){const c=this.ctx;c.fillStyle="#15130f";c.fillRect(0,0,this.wellW,this.wellH);c.strokeStyle="rgba(236,228,209,.07)";c.lineWidth=1;for(let x=1;x<COLS;x++){c.beginPath();c.moveTo(x*this.cell,0);c.lineTo(x*this.cell,this.wellH);c.stroke();}for(let y=1;y<VISIBLE_ROWS;y++){c.beginPath();c.moveTo(0,y*this.cell);c.lineTo(this.wellW,y*this.cell);c.stroke();}const heightY=this.wellH*(1-clock.boardHeight/100);c.fillStyle="rgba(189,85,62,.07)";c.fillRect(0,heightY,this.wellW,this.wellH-heightY);c.strokeStyle=this.fg;c.globalAlpha=.55+clock.kickPulse*.35;c.lineWidth=2;c.strokeRect(1,1,this.wellW-2,this.wellH-2);c.globalAlpha=1;}
  private block(x:number,y:number,type:PieceId,alpha:number,flash:number){const c=this.ctx,p=Math.max(1,Math.floor(this.cell*.06)),px=x*this.cell+p,py=y*this.cell+p,s=this.cell-p*2;c.globalAlpha=alpha;c.fillStyle=this.colors[type];c.fillRect(px,py,s,s);c.fillStyle="rgba(255,255,255,.17)";c.fillRect(px,py,s,Math.max(1,s*.2));c.fillStyle="rgba(0,0,0,.22)";c.fillRect(px,py+s*.8,s,Math.max(1,s*.2));if(flash){c.fillStyle=`rgba(255,255,255,${flash*.45})`;c.fillRect(px,py,s,s);}c.globalAlpha=1;}
  private outline(x:number,y:number,type:PieceId){const c=this.ctx,p=3;c.strokeStyle=this.colors[type];c.globalAlpha=.35;c.strokeRect(x*this.cell+p+.5,y*this.cell+p+.5,this.cell-p*2-1,this.cell-p*2-1);c.globalAlpha=1;}
  private scan(clock:MusicClock){const c=this.ctx,seqTop=(VISIBLE_ROWS-SEQUENCE_STEPS)*this.cell,lineY=seqTop+(SEQUENCE_STEPS-(clock.step+clock.frac))*this.cell;c.strokeStyle=this.fg;c.globalAlpha=.85;c.lineWidth=2;c.beginPath();c.moveTo(0,lineY);c.lineTo(this.wellW,lineY);c.stroke();c.globalAlpha=1;}
  private particles(juice:Juice){const c=this.ctx;for(const p of juice.particles){c.save();c.translate(p.x-this.ox,p.y-this.oy);c.rotate(p.rot);c.globalAlpha=Math.max(0,p.life/p.max);c.fillStyle=p.color;c.fillRect(-p.w/2,-p.h/2,p.w,p.h);c.restore();}c.font=`600 ${Math.max(11,this.cell*.5)}px system-ui`;c.textAlign="center";for(const f of juice.floaters){c.globalAlpha=Math.max(0,f.life/f.max);c.fillStyle=this.fg;c.fillText(f.text,f.x-this.ox,f.y-this.oy);}c.globalAlpha=1;c.textAlign="left";}
}
